export const DEFAULT_TABLES = Array.from({ length: 70 }, (_, i) => ({
  id: i + 1,
  name: `طاولة ${i + 1}`,
  seats: i < 30 ? 4 : i < 55 ? 6 : 8,
  area: i < 35 ? 'indoor' : i < 55 ? 'outdoor' : 'terrace',
  status: 'empty',
  currentOrder: [],
  notes: '',
  subtotal: 0,
  tax: 0,
  serviceCharge: 0,
  total: 0,
  waiterCode: null,
  seatedAt: null,
  guests: 0
}));

export const DEFAULT_DEPARTMENTS = [
  {
    id: 'kitchen',
    name: 'المطبخ',
    nameEn: 'Kitchen',
    icon: 'chef-hat',
    image: 'chef-hat',
    color: '#e67e22',
    description: 'قسم الطعام الرئيسي والوجبات',
    workHours: '08:00 - 23:00',
    activeOrders: 0,
    lastOrderAt: null
  },
  {
    id: 'bar',
    name: 'البار',
    nameEn: 'Bar',
    icon: 'cup-soda',
    image: 'cup-soda',
    color: '#1abc9c',
    description: 'قسم المشروبات والعصائر',
    workHours: '08:00 - 24:00',
    activeOrders: 0,
    lastOrderAt: null
  },
  {
    id: 'shisha',
    name: 'الشيشة',
    nameEn: 'Shisha',
    icon: 'wind',
    image: 'wind',
    color: '#27ae60',
    description: 'قسم الشيشة والأرجيلة',
    workHours: '14:00 - 02:00',
    activeOrders: 0,
    lastOrderAt: null
  }
];

export const DEFAULT_MENU = [
  {
    "id": "sm-3089",
    "nameAr": "خبز الثوم",
    "nameEn": "",
    "name": "خبز الثوم",
    "category": "appetizers",
    "price": 12,
    "description": "مقبلات - Soul Mate",
    "image": "utensils",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-3101",
    "nameAr": "حلقات بصل",
    "nameEn": "",
    "name": "حلقات بصل",
    "category": "appetizers",
    "price": 12,
    "description": "مقبلات - Soul Mate",
    "image": "utensils",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-3090",
    "nameAr": "زيتون مقلي",
    "nameEn": "",
    "name": "زيتون مقلي",
    "category": "appetizers",
    "price": 12,
    "description": "مقبلات - Soul Mate",
    "image": "utensils",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-3092",
    "nameAr": "أصابع جبنة",
    "nameEn": "",
    "name": "أصابع جبنة",
    "category": "appetizers",
    "price": 15,
    "description": "مقبلات - Soul Mate",
    "image": "utensils",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-3091",
    "nameAr": "أصابع دجاج بالسمسم",
    "nameEn": "",
    "name": "أصابع دجاج بالسمسم",
    "category": "appetizers",
    "price": 20,
    "description": "مقبلات - Soul Mate",
    "image": "utensils",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "paper-sand-mushroom",
    "nameAr": "دجاج بالمشروم",
    "nameEn": "",
    "name": "دجاج بالمشروم",
    "category": "sandwiches",
    "price": 39,
    "description": "ساندويتشات - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69e496292c06d.jpg",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-2363",
    "nameAr": "دجاج بالجبنة",
    "nameEn": "",
    "name": "دجاج بالجبنة",
    "category": "sandwiches",
    "price": 39,
    "description": "ساندويتشات - Soul Mate",
    "image": "https://kitchen.sayidaty.net/uploads/small/1e/1ee4d1babcf4bb2ee2288fd7690f30f5_w750_h500.jpg",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-2365",
    "nameAr": "دجاج بالكاري",
    "nameEn": "",
    "name": "دجاج بالكاري",
    "category": "sandwiches",
    "price": 39,
    "description": "ساندويتشات - Soul Mate",
    "image": "https://kitchen.sayidaty.net/uploads/small/54/54df474f0b01b344284e529c6521a9d2_w750_h500.jpg",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-2366",
    "nameAr": "دجاج الذرة",
    "nameEn": "",
    "name": "دجاج الذرة",
    "category": "sandwiches",
    "price": 39,
    "description": "ساندويتشات - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c2759ba7d7f.png",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-2368",
    "nameAr": "دجاج سكلوبيني",
    "nameEn": "",
    "name": "دجاج سكلوبيني",
    "category": "sandwiches",
    "price": 39,
    "description": "ساندويتشات - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c2761b4259e.png",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-2370",
    "nameAr": "صدر دجاج مشوي",
    "nameEn": "",
    "name": "صدر دجاج مشوي",
    "category": "sandwiches",
    "price": 35,
    "description": "ساندويتشات - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27675427fa.jpg",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-2367",
    "nameAr": "دجاج بانيه",
    "nameEn": "",
    "name": "دجاج بانيه",
    "category": "sandwiches",
    "price": 35,
    "description": "ساندويتشات - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c275d551ad1.jpg",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-2364",
    "nameAr": "تشكن بيتزا",
    "nameEn": "",
    "name": "تشكن بيتزا",
    "category": "sandwiches",
    "price": 39,
    "description": "ساندويتشات - Soul Mate",
    "image": "https://th.bing.com/th/id/R.ba6edc021d35ea387cb1a2a5d3b9285b?rik=gjDyAUinCWXnTw&pid=ImgRaw&r=0",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-2369",
    "nameAr": "تشكن راب مكسيكي",
    "nameEn": "",
    "name": "تشكن راب مكسيكي",
    "category": "sandwiches",
    "price": 39,
    "description": "ساندويتشات - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c2764e8d272.png",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "paper-crispy-chicken-sandwich",
    "nameAr": "دجاج كرسبي",
    "nameEn": "",
    "name": "دجاج كرسبي",
    "category": "sandwiches",
    "price": 39,
    "description": "ساندويتشات - Soul Mate",
    "image": "utensils",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-3132",
    "nameAr": "فطور Soul Mate",
    "nameEn": "",
    "name": "فطور Soul Mate",
    "category": "breakfast",
    "price": 40,
    "description": "إفطار فلسطيني - Soul Mate",
    "image": "utensils",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-3099",
    "nameAr": "إيطالي",
    "nameEn": "",
    "name": "إيطالي",
    "category": "breakfast",
    "price": 25,
    "description": "إفطار فلسطيني - Soul Mate",
    "image": "utensils",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-3100",
    "nameAr": "بيتزا باجيت",
    "nameEn": "",
    "name": "بيتزا باجيت",
    "category": "breakfast",
    "price": 25,
    "description": "إفطار فلسطيني - Soul Mate",
    "image": "utensils",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-3072",
    "nameAr": "دجاج سكلوبيني",
    "nameEn": "",
    "name": "دجاج سكلوبيني",
    "category": "mains",
    "price": 65,
    "description": "وجبات رئيسية - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69e495f9e4296.jpg",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-3074",
    "nameAr": "دجاج بالمشروم",
    "nameEn": "",
    "name": "دجاج بالمشروم",
    "category": "mains",
    "price": 59,
    "description": "وجبات رئيسية - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69e496292c06d.jpg",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "paper-main-mexican-chicken",
    "nameAr": "دجاج بالمكسيكي",
    "nameEn": "",
    "name": "دجاج بالمكسيكي",
    "category": "mains",
    "price": 55,
    "description": "وجبات رئيسية - Soul Mate",
    "image": "utensils",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-3076",
    "nameAr": "دجاج بانيه",
    "nameEn": "",
    "name": "دجاج بانيه",
    "category": "mains",
    "price": 55,
    "description": "وجبات رئيسية - Soul Mate",
    "image": "utensils",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-3073",
    "nameAr": "دجاج ستروغونوف",
    "nameEn": "",
    "name": "دجاج ستروغونوف",
    "category": "mains",
    "price": 59,
    "description": "وجبات رئيسية - Soul Mate",
    "image": "utensils",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "paper-main-shish-tawook",
    "nameAr": "شيش طاووق",
    "nameEn": "",
    "name": "شيش طاووق",
    "category": "mains",
    "price": 55,
    "description": "وجبات رئيسية - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27690d01a0.jpg",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "paper-main-spicy-satay",
    "nameAr": "تشكن ستاوي حار",
    "nameEn": "",
    "name": "تشكن ستاوي حار",
    "category": "mains",
    "price": 59,
    "description": "وجبات رئيسية - Soul Mate",
    "image": "utensils",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-3077",
    "nameAr": "كوردن بلو",
    "nameEn": "",
    "name": "كوردن بلو",
    "category": "mains",
    "price": 65,
    "description": "وجبات رئيسية - Soul Mate",
    "image": "utensils",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "paper-western-fattoush",
    "nameAr": "فتوش",
    "nameEn": "",
    "name": "فتوش",
    "category": "salads_western",
    "price": 20,
    "description": "سلطات غربية - Soul Mate",
    "image": "salad",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-3080",
    "nameAr": "سلطة يونانية",
    "nameEn": "",
    "name": "سلطة يونانية",
    "category": "salads_western",
    "price": 25,
    "description": "سلطات غربية - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69e0b6089f2fd.jpg",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "paper-western-russian-salad",
    "nameAr": "سلطة روسية",
    "nameEn": "",
    "name": "سلطة روسية",
    "category": "salads_western",
    "price": 25,
    "description": "سلطات غربية - Soul Mate",
    "image": "salad",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-3083",
    "nameAr": "سلطة سيزر",
    "nameEn": "",
    "name": "سلطة سيزر",
    "category": "salads_western",
    "price": 25,
    "description": "سلطات غربية - Soul Mate",
    "image": "utensils",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-3102",
    "nameAr": "سلطة سيزر دجاج",
    "nameEn": "",
    "name": "سلطة سيزر دجاج",
    "category": "salads_western",
    "price": 28,
    "description": "سلطات غربية - Soul Mate",
    "image": "utensils",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-3081",
    "nameAr": "سلطة حلوم",
    "nameEn": "",
    "name": "سلطة حلوم",
    "category": "salads_western",
    "price": 25,
    "description": "سلطات غربية - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69e0b63c14f61.jpg",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-3082",
    "nameAr": "سلطة جرجير",
    "nameEn": "",
    "name": "سلطة جرجير",
    "category": "salads_western",
    "price": 25,
    "description": "سلطات غربية - Soul Mate",
    "image": "utensils",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-3084",
    "nameAr": "سلطة Soul Mate",
    "nameEn": "",
    "name": "سلطة Soul Mate",
    "category": "salads_western",
    "price": 25,
    "description": "سلطات غربية - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69e0b9bac4815.jpg",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "paper-east-green-salad",
    "nameAr": "سلطة خضرة",
    "nameEn": "",
    "name": "سلطة خضرة",
    "category": "salads_eastern",
    "price": 10,
    "description": "السلطات الشرقية - Soul Mate",
    "image": "salad",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "paper-east-butter-corn",
    "nameAr": "ذرة بالزبدة",
    "nameEn": "",
    "name": "ذرة بالزبدة",
    "category": "salads_eastern",
    "price": 8,
    "description": "السلطات الشرقية - Soul Mate",
    "image": "salad",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "paper-east-mayo-corn",
    "nameAr": "ذرة بالمايونيز",
    "nameEn": "",
    "name": "ذرة بالمايونيز",
    "category": "salads_eastern",
    "price": 6,
    "description": "السلطات الشرقية - Soul Mate",
    "image": "salad",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "paper-east-hummus-mutabbal",
    "nameAr": "متبل حمص",
    "nameEn": "",
    "name": "متبل حمص",
    "category": "salads_eastern",
    "price": 6,
    "description": "السلطات الشرقية - Soul Mate",
    "image": "salad",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "paper-east-coleslaw",
    "nameAr": "كولسلو",
    "nameEn": "",
    "name": "كولسلو",
    "category": "salads_eastern",
    "price": 6,
    "description": "السلطات الشرقية - Soul Mate",
    "image": "salad",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "paper-east-hummus",
    "nameAr": "حمص",
    "nameEn": "",
    "name": "حمص",
    "category": "salads_eastern",
    "price": 6,
    "description": "السلطات الشرقية - Soul Mate",
    "image": "salad",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "paper-east-avocado",
    "nameAr": "أفوكادو",
    "nameEn": "",
    "name": "أفوكادو",
    "category": "salads_eastern",
    "price": 5,
    "description": "السلطات الشرقية - Soul Mate",
    "image": "salad",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "paper-east-pickles",
    "nameAr": "مخللات",
    "nameEn": "",
    "name": "مخللات",
    "category": "salads_eastern",
    "price": 4,
    "description": "السلطات الشرقية - Soul Mate",
    "image": "salad",
    "department": "kitchen",
    "available": true,
    "prepTime": 15
  },
  {
    "id": "sm-2346",
    "nameAr": "شاي بالكب",
    "nameEn": "",
    "name": "شاي بالكب",
    "category": "hot_drinks",
    "price": 8,
    "description": "مشروبات ساخنة - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69bfedeac3900.jpg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "paper-hot-herbs",
    "nameAr": "أعشاب",
    "nameEn": "",
    "name": "أعشاب",
    "category": "hot_drinks",
    "price": 8,
    "description": "مشروبات ساخنة - Soul Mate",
    "image": "coffee",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "paper-hot-herbs-honey",
    "nameAr": "أعشاب بالعسل",
    "nameEn": "",
    "name": "أعشاب بالعسل",
    "category": "hot_drinks",
    "price": 8,
    "description": "مشروبات ساخنة - Soul Mate",
    "image": "coffee",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2347",
    "nameAr": "قهوة تركي صغير",
    "nameEn": "",
    "name": "قهوة تركي صغير",
    "category": "hot_drinks",
    "price": 8,
    "description": "مشروبات ساخنة - Soul Mate",
    "image": "https://yummy.awicdn.com/site-images/sites/default/files/prod/recipe/2/0/610820/0a81c1c9afc5cf7807a31eb57d9b29dc1e676d77-051023082901.jpg?preset=v3.0_970XDYN&save-png=1&rnd=1519151RND220215",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2348",
    "nameAr": "قهوة تركي كبير",
    "nameEn": "",
    "name": "قهوة تركي كبير",
    "category": "hot_drinks",
    "price": 10,
    "description": "مشروبات ساخنة - Soul Mate",
    "image": "https://tse4.mm.bing.net/th/id/OIP.kPw-uW0dj5iFOpRZhaIp_AHaD4?w=600&h=314&rs=1&pid=ImgDetMain&o=7&rm=3",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-3095",
    "nameAr": "اسبريسو صغير",
    "nameEn": "",
    "name": "اسبريسو صغير",
    "category": "hot_drinks",
    "price": 10,
    "description": "مشروبات ساخنة - Soul Mate",
    "image": "utensils",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2349",
    "nameAr": "اسبريسو كبير",
    "nameEn": "",
    "name": "اسبريسو كبير",
    "category": "hot_drinks",
    "price": 12,
    "description": "مشروبات ساخنة - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27e61b8194.jpg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2350",
    "nameAr": "نسكافيه",
    "nameEn": "",
    "name": "نسكافيه",
    "category": "hot_drinks",
    "price": 10,
    "description": "مشروبات ساخنة - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27e4132338.webp",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-3096",
    "nameAr": "هوت شوكلت",
    "nameEn": "",
    "name": "هوت شوكلت",
    "category": "hot_drinks",
    "price": 10,
    "description": "مشروبات ساخنة - Soul Mate",
    "image": "utensils",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2351",
    "nameAr": "كابتشينو",
    "nameEn": "",
    "name": "كابتشينو",
    "category": "hot_drinks",
    "price": 12,
    "description": "مشروبات ساخنة - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27e1487ddf.jpg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "paper-hot-cafe-latte",
    "nameAr": "كافيه لاتيه",
    "nameEn": "",
    "name": "كافيه لاتيه",
    "category": "hot_drinks",
    "price": 12,
    "description": "مشروبات ساخنة - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27e1487ddf.jpg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2352",
    "nameAr": "كافيه موكا",
    "nameEn": "",
    "name": "كافيه موكا",
    "category": "hot_drinks",
    "price": 15,
    "description": "مشروبات ساخنة - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27af996bd5.jpg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2356",
    "nameAr": "كافيه نوتيلا",
    "nameEn": "",
    "name": "كافيه نوتيلا",
    "category": "hot_drinks",
    "price": 15,
    "description": "مشروبات ساخنة - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69bff3fcbd9ca.jpg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2357",
    "nameAr": "كافيه لوتس",
    "nameEn": "",
    "name": "كافيه لوتس",
    "category": "hot_drinks",
    "price": 15,
    "description": "مشروبات ساخنة - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27b56ca2f7.jpg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "paper-water-small",
    "nameAr": "مياه معدنية صغيرة",
    "nameEn": "",
    "name": "مياه معدنية صغيرة",
    "category": "cold_drinks",
    "price": 3,
    "description": "مشروبات باردة - Soul Mate",
    "image": "https://www.dokkanplus.com/storage/product/1OhtDhKCdwiYIF5dHltntSZYaSr6lGb5jwfljtqT.png",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2327",
    "nameAr": "مياه معدنية 500 مل",
    "nameEn": "",
    "name": "مياه معدنية 500 مل",
    "category": "cold_drinks",
    "price": 6,
    "description": "مشروبات باردة - Soul Mate",
    "image": "https://www.dokkanplus.com/storage/product/1OhtDhKCdwiYIF5dHltntSZYaSr6lGb5jwfljtqT.png",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "paper-cola-zero",
    "nameAr": "كولا زيرو",
    "nameEn": "",
    "name": "كولا زيرو",
    "category": "soft_drinks",
    "price": 10,
    "description": "مشروبات غازية - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27c5c10f8d.png",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2325",
    "nameAr": "فانتا",
    "nameEn": "",
    "name": "فانتا",
    "category": "soft_drinks",
    "price": 10,
    "description": "مشروبات غازية - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27c8ca87d0.png",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2326",
    "nameAr": "سبرايت",
    "nameEn": "",
    "name": "سبرايت",
    "category": "soft_drinks",
    "price": 10,
    "description": "مشروبات غازية - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27cc9d7084.png",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2324",
    "nameAr": "شويبس",
    "nameEn": "",
    "name": "شويبس",
    "category": "soft_drinks",
    "price": 12,
    "description": "مشروبات غازية - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69bfea4687059.jpg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2359",
    "nameAr": "بلو",
    "nameEn": "",
    "name": "بلو",
    "category": "soft_drinks",
    "price": 12,
    "description": "مشروبات غازية - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27cd437e96.png",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2322",
    "nameAr": "XL",
    "nameEn": "",
    "name": "XL",
    "category": "soft_drinks",
    "price": 12,
    "description": "مشروبات غازية - Soul Mate",
    "image": "https://p.globalsources.com/IMAGES/PDT/B5107283917/XL-energy-drink.jpg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2331",
    "nameAr": "ليمون بالنعنع",
    "nameEn": "",
    "name": "ليمون بالنعنع",
    "category": "cold_drinks",
    "price": 20,
    "description": "مشروبات باردة - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69e0b8f38d722.jpg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2332",
    "nameAr": "برتقال",
    "nameEn": "",
    "name": "برتقال",
    "category": "cold_drinks",
    "price": 20,
    "description": "مشروبات باردة - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69bfebd8e20cc.jpg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2333",
    "nameAr": "أناناس",
    "nameEn": "",
    "name": "أناناس",
    "category": "cold_drinks",
    "price": 20,
    "description": "مشروبات باردة - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69bfec6066658.jpg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2329",
    "nameAr": "فراولة",
    "nameEn": "",
    "name": "فراولة",
    "category": "cold_drinks",
    "price": 20,
    "description": "مشروبات باردة - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27ba155f02.jpg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2328",
    "nameAr": "مانجا",
    "nameEn": "",
    "name": "مانجا",
    "category": "cold_drinks",
    "price": 20,
    "description": "مشروبات باردة - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27b7eca9d4.webp",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2613",
    "nameAr": "كوكتيل",
    "nameEn": "",
    "name": "كوكتيل",
    "category": "cold_drinks",
    "price": 20,
    "description": "مشروبات باردة - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c3e77d4d9ee.jpeg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2335",
    "nameAr": "فخفخينا",
    "nameEn": "",
    "name": "فخفخينا",
    "category": "cold_drinks",
    "price": 22,
    "description": "مشروبات باردة - Soul Mate",
    "image": "https://th.bing.com/th/id/R.18ebab2daf043393d260b4a391df5b56?rik=PSbRlm9pNvQNmA&riu=http%3a%2f%2fnewsite.polarbear.co.in%2fwp-content%2fuploads%2f2022%2f03%2fOne-and-Only-Royal-Falooda.jpg&ehk=NIXHG7nzP84gj2Eq7yxIwCuETfVn8amuIDk%2bu6i5jfg%3d&risl=&pid=ImgRaw&r=0",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2337",
    "nameAr": "آيس كوفي",
    "nameEn": "",
    "name": "آيس كوفي",
    "category": "cold_drinks",
    "price": 20,
    "description": "مشروبات باردة - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69bfedc336a9e.jpg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2320",
    "nameAr": "ميلك شيك",
    "nameEn": "",
    "name": "ميلك شيك",
    "category": "cold_drinks",
    "price": 25,
    "description": "مشروبات باردة - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27a9bb5937.jpg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2307",
    "nameAr": "تشيز كيك",
    "nameEn": "",
    "name": "تشيز كيك",
    "category": "desserts",
    "price": 22,
    "description": "حلويات - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c3d8ba53905.jpeg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "paper-fruit-icecream-salad",
    "nameAr": "سلطة فواكه بالايس كريم",
    "nameEn": "",
    "name": "سلطة فواكه بالايس كريم",
    "category": "desserts",
    "price": 20,
    "description": "حلويات - Soul Mate",
    "image": "ice-cream",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "paper-black-forest",
    "nameAr": "بلاك فورست",
    "nameEn": "",
    "name": "بلاك فورست",
    "category": "desserts",
    "price": 25,
    "description": "حلويات - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c3d8ba53905.jpeg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "paper-nutella-clack",
    "nameAr": "كلاك نوتيلا",
    "nameEn": "",
    "name": "كلاك نوتيلا",
    "category": "desserts",
    "price": 25,
    "description": "حلويات - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27a77b2b48.webp",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2319",
    "nameAr": "كيك نوتيلا",
    "nameEn": "",
    "name": "كيك نوتيلا",
    "category": "desserts",
    "price": 25,
    "description": "حلويات - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27a77b2b48.webp",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2311",
    "nameAr": "كنافة نوتيلا",
    "nameEn": "",
    "name": "كنافة نوتيلا",
    "category": "desserts",
    "price": 22,
    "description": "حلويات - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69bfe62d0411e.jpg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2312",
    "nameAr": "كريب",
    "nameEn": "",
    "name": "كريب",
    "category": "desserts",
    "price": 28,
    "description": "حلويات - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c3e4220979f.jpeg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-3094",
    "nameAr": "كريب مكس",
    "nameEn": "",
    "name": "كريب مكس",
    "category": "desserts",
    "price": 32,
    "description": "حلويات - Soul Mate",
    "image": "utensils",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2316",
    "nameAr": "وافل",
    "nameEn": "",
    "name": "وافل",
    "category": "desserts",
    "price": 28,
    "description": "حلويات - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27a3942971.webp",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-3093",
    "nameAr": "وافل مكس",
    "nameEn": "",
    "name": "وافل مكس",
    "category": "desserts",
    "price": 32,
    "description": "حلويات - Soul Mate",
    "image": "utensils",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2314",
    "nameAr": "بان كيك",
    "nameEn": "",
    "name": "بان كيك",
    "category": "desserts",
    "price": 28,
    "description": "حلويات - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69c27a18bf9a5.jpg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "paper-ice-cream",
    "nameAr": "آيس كريم",
    "nameEn": "",
    "name": "آيس كريم",
    "category": "desserts",
    "price": 25,
    "description": "حلويات - Soul Mate",
    "image": "ice-cream",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-3103",
    "nameAr": "حلا Soul Mate",
    "nameEn": "",
    "name": "حلا Soul Mate",
    "category": "desserts",
    "price": 30,
    "description": "حلويات - Soul Mate",
    "image": "https://meedmenu.com/uploads/products/69dfb4e029625.jpg",
    "department": "bar",
    "available": true,
    "prepTime": 5
  },
  {
    "id": "sm-2338",
    "nameAr": "ميزو",
    "nameEn": "",
    "name": "ميزو",
    "category": "shisha",
    "price": 80,
    "description": "أراجيل - Soul Mate",
    "image": "https://www.alshahm-plastic.com/wp-content/uploads/2024/05/ca718b5f36.png",
    "department": "shisha",
    "available": true,
    "prepTime": 10
  },
  {
    "id": "sm-2339",
    "nameAr": "فاخر",
    "nameEn": "",
    "name": "فاخر",
    "category": "shisha",
    "price": 85,
    "description": "أراجيل - Soul Mate",
    "image": "https://www.alshahm-plastic.com/wp-content/uploads/2024/05/ca718b5f36.png",
    "department": "shisha",
    "available": true,
    "prepTime": 10
  },
  {
    "id": "sm-2342",
    "nameAr": "تيربو",
    "nameEn": "",
    "name": "تيربو",
    "category": "shisha",
    "price": 80,
    "description": "أراجيل - Soul Mate",
    "image": "https://www.alshahm-plastic.com/wp-content/uploads/2024/05/ca718b5f36.png",
    "department": "shisha",
    "available": true,
    "prepTime": 10
  },
  {
    "id": "sm-2343",
    "nameAr": "سراب",
    "nameEn": "",
    "name": "سراب",
    "category": "shisha",
    "price": 80,
    "description": "أراجيل - Soul Mate",
    "image": "https://www.alshahm-plastic.com/wp-content/uploads/2024/05/ca718b5f36.png",
    "department": "shisha",
    "available": true,
    "prepTime": 10
  },
  {
    "id": "paper-shisha-grape-mint",
    "nameAr": "عنب ونعنع",
    "nameEn": "",
    "name": "عنب ونعنع",
    "category": "shisha",
    "price": 85,
    "description": "أراجيل - Soul Mate",
    "image": "https://www.alshahm-plastic.com/wp-content/uploads/2024/05/ca718b5f36.png",
    "department": "shisha",
    "available": true,
    "prepTime": 10
  },
  {
    "id": "paper-shisha-two-apples",
    "nameAr": "تفاحتين",
    "nameEn": "",
    "name": "تفاحتين",
    "category": "shisha",
    "price": 85,
    "description": "أراجيل - Soul Mate",
    "image": "https://www.alshahm-plastic.com/wp-content/uploads/2024/05/ca718b5f36.png",
    "department": "shisha",
    "available": true,
    "prepTime": 10
  },
  {
    "id": "paper-glass-fakher",
    "nameAr": "فاخر زجاج",
    "nameEn": "",
    "name": "فاخر زجاج",
    "category": "shisha",
    "price": 110,
    "description": "أراجيل - Soul Mate",
    "image": "https://www.alshahm-plastic.com/wp-content/uploads/2024/05/ca718b5f36.png",
    "department": "shisha",
    "available": true,
    "prepTime": 10
  },
  {
    "id": "paper-glass-grape-mint",
    "nameAr": "عنب ونعنع زجاج",
    "nameEn": "",
    "name": "عنب ونعنع زجاج",
    "category": "shisha",
    "price": 110,
    "description": "أراجيل - Soul Mate",
    "image": "https://www.alshahm-plastic.com/wp-content/uploads/2024/05/ca718b5f36.png",
    "department": "shisha",
    "available": true,
    "prepTime": 10
  },
  {
    "id": "paper-glass-two-apples",
    "nameAr": "تفاحتين زجاج",
    "nameEn": "",
    "name": "تفاحتين زجاج",
    "category": "shisha",
    "price": 110,
    "description": "أراجيل - Soul Mate",
    "image": "https://www.alshahm-plastic.com/wp-content/uploads/2024/05/ca718b5f36.png",
    "department": "shisha",
    "available": true,
    "prepTime": 10
  },
  {
    "id": "sm-2373",
    "nameAr": "خدمة شيشة",
    "nameEn": "",
    "name": "خدمة شيشة",
    "category": "shisha_addons",
    "price": 30,
    "description": "إضافات الأراجيل - Soul Mate",
    "image": "https://t4.ftcdn.net/jpg/05/26/89/27/360_F_526892727_iLTOI43LSyN9vSGm9W2d2vyDXw7Crrel.jpg",
    "department": "shisha",
    "available": true,
    "prepTime": 10
  },
  {
    "id": "sm-2374",
    "nameAr": "خرطوم صحي",
    "nameEn": "",
    "name": "خرطوم صحي",
    "category": "shisha_addons",
    "price": 25,
    "description": "إضافات الأراجيل - Soul Mate",
    "image": "https://tse3.mm.bing.net/th/id/OIP.A3f6Ngv0XCjN2dp5N56ABQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
    "department": "shisha",
    "available": true,
    "prepTime": 10
  }
];

export const DEFAULT_EMPLOYEES = [
  { id: 'admin-1', name: 'مدير تكة', nameEn: 'Taka Manager', role: 'manager', username: 'admin', password: 'admin123', code: 'ADMIN', phone: '0790000000', email: 'admin@taka.com', salary: 0, active: true, lastLogin: null },
  { id: 'waiter-1', name: 'أحمد الجرسون', nameEn: 'Ahmed Waiter', role: 'waiter', username: 'waiter1', password: '1234', code: 'W-1234', phone: '0791234567', email: 'waiter1@taka.com', salary: 500, active: true, lastLogin: null },
  { id: 'cashier-1', name: 'سارة المحاسبة', nameEn: 'Sara Cashier', role: 'cashier', username: 'cashier1', password: '1234', code: 'C-5678', phone: '0781234567', email: 'cashier1@taka.com', salary: 600, active: true, lastLogin: null },
  { id: 'kitchen-1', name: 'خالد الطباخ', nameEn: 'Khaled Cook', role: 'kitchen', username: 'kitchen1', password: '1234', code: 'K-1111', phone: '0771111111', email: 'kitchen1@taka.com', salary: 550, active: true, lastLogin: null },
  { id: 'bar-1', name: 'محمد البار', nameEn: 'Mohammed Bar', role: 'bar', username: 'bar1', password: '1234', code: 'B-2222', phone: '0772222222', email: 'bar1@taka.com', salary: 480, active: true, lastLogin: null },
  { id: 'shisha-1', name: 'علي الشيشة', nameEn: 'Ali Shisha', role: 'shisha', username: 'shisha1', password: '1234', code: 'S-3333', phone: '0773333333', email: 'shisha1@taka.com', salary: 450, active: true, lastLogin: null }
];
